services:
  postgres:
    image: 'postgres:13'
    container_name: docker-postgres-registration
    environment:
      - 'POSTGRES_DB=registration'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'