services:
  postgres:
    image: 'postgres:latest'
    container_name: 'docker-postgres-registration'
    environment:
      - 'POSTGRES_DB=registration'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - '8000:5432'